version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trix-frontend-docker
    ports:
      - 80:80
    volumes:
      - .:/app
      - ./build:/usr/share/nginx/html